### ISSUE TITLE
Unhandled error after updating Windows 11 to 22H2

### ISSUE THREAD

**Issue by forditohu** [zgdump/windows-virtualdesktopindicator#20]
![image](https://user-images.githubusercontent.com/115089187/194074639-0c522ed7-d97d-4a14-95f4-4ceca7e3249f.png)

---------------------------
VirtualDesktopIndicator
---------------------------
VirtualDesktopIndicator encountered an unhandled error:
System.Runtime.InteropServices.COMException (0x800706F4): A null reference pointer was passed to the stub. (0x800706F4)

   at VirtualDesktopIndicator.Native.VirtualDesktop.Implementation.VirtualDesktopWin11.IVirtualDesktopManagerInternal.GetDesktops(IntPtr hWnd, IObjectArray& desktops)

   at VirtualDesktopIndicator.Native.VirtualDesktop.Implementation.VirtualDesktopWin11.DesktopManager.GetDesktopIndex(IVirtualDesktop desktop) in C:\Users\Valery\Desktop\windows-virtualdesktopindicator\src\Native\VirtualDesktop\Implementation\VirtualDesktopWin11.cs:line 251

   at VirtualDesktopIndicator.Native.VirtualDesktop.Implementation.VirtualDesktopWin11.Current() in C:\Users\Valery\Desktop\windows-virtualdesktopindicator\src\Native\VirtualDesktop\Implementation\VirtualDesktopWin11.cs:line 11

   at VirtualDesktopIndicator.Components.DesktopNotifyIcon.get_CurrentVirtualDesktop() in C:\Users\Valery\Desktop\windows-virtualdesktopindicator\src\Components\DesktopNotifyIcon.cs:line 117

   at VirtualDesktopIndicator.Components.DesktopNotifyIcon.OnTimerTick(Object sender, EventArgs e) in C:\Users\Valery\Desktop\windows-virtualdesktopindicator\src\Components\DesktopNotifyIcon.cs:line 260
---------------------------
OK   
---------------------------

**Comment by forditohu** [comment]
Duplicate, sorry
